var cityData = {
    osk:{
        osakaMetro:{
            M:{
                url:"https://namu.wiki/w/%EC%98%A4%EC%82%AC%EC%B9%B4%20%EB%A9%94%ED%8A%B8%EB%A1%9C%20%EB%AF%B8%EB%8F%84%EC%8A%A4%EC%A7%80%EC%84%A0",
                name:{
                    ko:"미도스지선",
                    en:"Midōsuji Line",
                    jp:"御堂筋線"
                },
                code:{
                    en:"M",
                    no:1
                },
                color:"#CC0000"
            },
            T:{
                url:"https://namu.wiki/w/%EC%98%A4%EC%82%AC%EC%B9%B4%20%EB%A9%94%ED%8A%B8%EB%A1%9C%20%ED%83%80%EB%8B%88%EB%A7%88%EC%B9%98%EC%84%A0",
                name:{
                    ko:"타니마치선",
                    en:"Tanimachi Line",
                    jp:"谷町線"
                },
                code:{
                    en:"T",
                    no:2
                },
                color:"#660066"
            },
            Y:{
                url:"https://namu.wiki/w/%EC%98%A4%EC%82%AC%EC%B9%B4%20%EB%A9%94%ED%8A%B8%EB%A1%9C%20%EC%9A%94%EC%B8%A0%EB%B0%94%EC%8B%9C%EC%84%A0",
                name:{
                    ko:"요츠바치선",
                    en:"Yotsubashi Line",
                    jp:"四つ橋"
                },
                code:{
                    en:"Y",
                    no:3
                },
                color:"#0066CC"
            },
            C:{
                url:"https://namu.wiki/w/%EC%98%A4%EC%82%AC%EC%B9%B4%20%EB%A9%94%ED%8A%B8%EB%A1%9C%20%EC%B8%84%EC%98%A4%EC%84%A0",
                name:{
                    ko:"츄오선",
                    en:"Chūō Line",
                    jp:"中央線"
                },
                code:{
                    en:"C",
                    no:4
                },
                color:"#009900"
            },
            S:{
                url:"https://namu.wiki/w/%EC%98%A4%EC%82%AC%EC%B9%B4%20%EB%A9%94%ED%8A%B8%EB%A1%9C%20%EC%84%BC%EB%8B%88%EC%B9%98%EB%A7%88%EC%97%90%EC%84%A0",
                name:{
                    ko:"센니치마에선",
                    en:"Sennichimae Line",
                    jp:"千日前線"
                },
                code:{
                    en:"S",
                    no:5
                },
                color:"#FF3366"
            },
            K:{
                url:"https://namu.wiki/w/%EC%98%A4%EC%82%AC%EC%B9%B4%20%EB%A9%94%ED%8A%B8%EB%A1%9C%20%EC%82%AC%EC%B9%B4%EC%9D%B4%EC%8A%A4%EC%A7%80%EC%84%A0",
                name:{
                    ko:"사카이스지선",
                    en:"SaKaisuji Line",
                    jp:"堺筋線"
                },
                code:{
                    en:"K",
                    no:6
                },
                color:"#663300"
            },
            N:{
                url:"https://namu.wiki/w/%EC%98%A4%EC%82%AC%EC%B9%B4%20%EB%A9%94%ED%8A%B8%EB%A1%9C%20%EB%82%98%EA%B0%80%ED%98%B8%EB%A6%AC%EC%B8%A0%EB%A3%A8%EB%AF%B8%EB%A3%8C%EC%BF%A0%EC%B9%98%EC%84%A0",
                name:{
                    ko:"나가호리츠루미료쿠치선",
                    en:"Nagahori Tsurumi-ryokuchi Line",
                    jp:"長堀鶴見緑地線"
                },
                code:{
                    en:"N",
                    no:7
                },
                color:"#CCFF33",
                fontBlack:true
            },
            I:{
                url:"https://namu.wiki/w/%EC%98%A4%EC%82%AC%EC%B9%B4%20%EB%A9%94%ED%8A%B8%EB%A1%9C%20%EC%9D%B4%EB%A7%88%EC%9E%90%ED%86%A0%EC%8A%A4%EC%A7%80%EC%84%A0",
                name:{
                    ko:"이마자토스지선",
                    en:"Imazatosuji Line",
                    jp:"今里筋線"
                },
                code:{
                    en:"I",
                    no:8
                },
                color:"#FF9900",
                fontBlack:true
            },
            P:{
                url:"https://namu.wiki/w/%EC%98%A4%EC%82%AC%EC%B9%B4%20%EB%A9%94%ED%8A%B8%EB%A1%9C%20%EB%82%9C%EC%BD%94%20%ED%8F%AC%ED%8A%B8%ED%83%80%EC%9A%B4%EC%84%A0",
                name:{
                    ko:"난코 포트타운선",
                    en:"Nankō Port Town Line",
                    jp:"南港ポートタウン線"
                },
                code:{
                    en:"P",
                    no:9
                },
                color:"#0099FF"
            }
        }
    }
}
